INSERT INTO TCHR VALUES('T038','SASI','CS','C++');
INSERT INTO TCHR VALUES('T042','JEYASUDHA','SCIENCE','MATHS');
INSERT INTO TCHR VALUES('T054','SUNDARAM','CS','AI');
INSERT INTO TCHR VALUES('T102','BHARGABI','SCIENCE','CHEM');
INSERT INTO TCHR VALUES('T076','SENTHIL','SCIENCE','PHY');
INSERT INTO TCHR VALUES('T045','REKHA','CS','C++');

SELECT * FROM TCHR;